### ISSUE TITLE
Tumbleweed installer runs out of memory with provided memory configuration

### ISSUE THREAD

**Issue by hydandata** [openSUSE/vagrant#1]
Apparently 512 is not enough for the installer.

**Comment by tboerger** [comment]
I'm working on the definitions now. I already increased the memory locally to 1GB and I made it configurable through user variables. If everything builds fine locally I will publish the base images on atlas as well.

**Comment by tboerger** [comment]
You can build it with `packer build -var 'memory=2048' definitions/tumbleweed-x86_64.json` now. The default value is `1024`. Maybe there are errors while building it, I need to wait for `systemsmanagement:chef:12` builds to try it finally if everything is working as expected.

I will close the issue for now, feel free to reopen it if something doesn't work.
