### ISSUE TITLE
openSUSE 42.2 version 1.0.2 stuck 1m 30s on first boot

### ISSUE THREAD

**Issue by reidrac** [openSUSE/vagrant#12]
Running:
```
vagrant init opensuse/openSUSE-42.2-x86_64
vagrant up
```

The image gets stuck during boot for 1 minute and 30 secs; the screen shows:
```
[ *** ] A start job is running for dev-system-swap.device (Xs / 1min 30s)
```

This is using Atlas image for openSUSE 42.2 version 1.0.2 with libvirt.

**Comment by hwoarang** [comment]
Thank you for the report.

The reason for this is that we do not create an LVM setup for the images but we rather use BTRFS. As such there is no /dev/system vg. Might actually be better to simply use /dev/sda1 for the swap device

**Comment by reidrac** [comment]
I'm not sure this helped; with libvirt now it gets stuck for 1:30 on:

``A start job is running for dev-sda1.device``

**Comment by reidrac** [comment]
Ah, libvirt shouldn't be using vda?

**Comment by hwoarang** [comment]
maybe. Never used it myself

**Comment by reidrac** [comment]
Yes, it should be vda1 instead of sda1. Just tested it and works as expected.

Thanks for the fix!
