### ISSUE TITLE
vboxsf module not loaded

### ISSUE THREAD

**Issue by Achimh3011** [openSUSE/vagrant#2]
Using the boxes in vagrant with the virtualbox provider gives an error as mounting shared directories from the host side fails. This is due to a kernel module not being loaded.

Maybe this needs to be fixed even further upstream, however the fix here the is to load the `vboxsf` kernel module upon system start.

``` diff
diff --git a/scripts/base/vmtools.sh b/scripts/base/vmtools.sh
index be7f020..fde236d 100755
--- a/scripts/base/vmtools.sh
+++ b/scripts/base/vmtools.sh
@@ -19,6 +19,7 @@ case "$PACKER_BUILDER_TYPE" in
       virtualbox-guest-tools \
       virtualbox-guest-x11 \
       virtualbox-guest-kmp-default
+    echo vboxsf >/etc/modules-load.d/vboxsf.conf
     ;;
 esac
```

See http://stackoverflow.com/questions/28328775/virtualbox-mount-vboxsf-mounting-failed-with-the-error-no-such-device#comment55725357_30388070

**Comment by tboerger** [comment]
Thanks, can you create a pull request for that since I'm on vacation?
