### ISSUE TITLE
Tumbleweed box download links don't work

### ISSUE THREAD

**Issue by zsoldosp** [openSUSE/vagrant#23]
(asof 2017 September 9 2:57 PM CET)

The link for e.g.: the tumbleweed virtualbox image is http://download.opensuse.org/vagrant/openSUSE-Tumbleweed-virtualbox-x86_64-1.0.1.box which gets redirected to ftp://ftp.suse.com/pub/projects/vagrant/openSUSE-Tumbleweed-virtualbox-x86_64-1.0.1.box which doesn't exist because ftp://ftp.suse.com/pub/projects/ has no `vagrant` folder

**Comment by hwoarang** [comment]
@zsoldosp I will build a new TW box and upload it to the vagrant website directly

**Comment by zsoldosp** [comment]
Thanks. 

re: title change - technically it also affects the 13.x boxes, though as those are EOL it's probably not an issue

**Comment by hwoarang** [comment]
@zsoldosp yeah I don't think there is any point in providing updated builds for these. I may as well remove them from the Atlas database.

**Comment by pavlix** [comment]
I'm getting redirected to ftp://ftp.suse.com/pub/projects/vagrant/openSUSE-Tumbleweed-virtualbox-x86_64-1.0.0.box which is defunct. Any plans to fix that?

    config.vm.box = "opensuse/openSUSE-Tumbleweed-x86_64"

**Comment by hwoarang** [comment]
@pavlix yeah it's on my todo to build new TW boxes this week
