### ISSUE TITLE
please add openSUSE 15 box

### ISSUE THREAD

**Issue by denisok** [openSUSE/vagrant#29]
Could we create openSUSE 15 box ?
It could be used for testing purposes before release.

**Comment by morawskim** [comment]
You can use my box (https://app.vagrantup.com/morawskim/boxes/openSUSE-15.0-x86_64-BETA)
I created provider only for virtualbox.
You can look at definition at my fork (https://github.com/morawskim/openSUSE-vagrant/tree/leap_15).

If you want build own box, remember that I have a issue with firewall. You must manually disable firewall.

**Comment by denisok** [comment]
so as 15 was released - could someone create 15 and push to the https://app.vagrantup.com/opensuse ? @hwoarang

**Comment by hwoarang** [comment]
I am in the process of building new boxes but I am investigating some issues with the libvirt box right now
