### ISSUE TITLE
Release 1.0.1

### ISSUE THREAD

**Issue by cocreature** [openSUSE/vagrant#4]
Version 1.0.1 which fixes an issue with loading `vboxfs` is currently marked as [unreleased](https://atlas.hashicorp.com/opensuse/boxes/openSUSE-42.1-x86_64) which makes me unable to use it. It would be great if you could flag it as released.

**Comment by tboerger** [comment]
I'm currently working on better official images built via our build service.

**Comment by matrixik** [comment]
Hello, any update on this?

**Comment by hwoarang** [comment]
I have released 1.0.1 so I am marking this as fixed
