### ISSUE TITLE
Hostname is not changed by Vagrant

### ISSUE THREAD

**Issue by electrocucaracha** [openSUSE/vagrant#41]
I'm using the [official Vagrant box](https://app.vagrantup.com/opensuse/boxes/openSUSE-Tumbleweed-Vagrant.x86_64) imaged published in the Vagrant Cloud website so I'm not sure if this is its source code  but if I use the following Vagrantfile:
```
Vagrant.configure("2") do |config|
  config.vm.box = "opensuse/openSUSE-Tumbleweed-Vagrant.x86_64"
  config.vm.box_version = "1.0.20190815"
  config.vm.hostname = "testing"
end
```
The hostname remains as  *localhost*
```
$ vagrant ssh
Have a lot of fun...
vagrant@localhost:~> hostnamectl 
   Static hostname: n/a
Transient hostname: localhost
         Icon name: computer-vm
           Chassis: vm
        Machine ID: f076b7f9485f4007b46843ea225a7d41
           Boot ID: ffe05284129e47d7928fb24ca0c87016
    Virtualization: kvm
  Operating System: openSUSE Tumbleweed
       CPE OS Name: cpe:/o:opensuse:tumbleweed:20190815
            Kernel: Linux 5.2.8-1-default
      Architecture: x86-64
```
As result, these VMs are only reachable through its IP address.

**Comment by dcermak** [comment]
@electrocucaracha Could you retry it with the `openSUSE/Tumbleweed.x86_64` box? I have made some changes with respect to the hostname in vagrant recently.

**Comment by electrocucaracha** [comment]
Hey @dcermak , thanks for responding to this issue. I just tried with the latest available box  but it seems like it's not setting up the host name.

```
$ cat Vagrantfile 
Vagrant.configure("2") do |config|
  config.vm.box = "opensuse/Tumbleweed.x86_64"
  config.vm.box_version = "1.0.20191110"
  config.vm.hostname = "testing"
end
$ vagrant ssh -- -t hostnamectl
   Static hostname: n/a
Transient hostname: localhost
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 08560f5137b643d9bb004bdee24ee10e
           Boot ID: 652ca5d5aa3a41c28b3c8c89c566f74d
    Virtualization: kvm
  Operating System: openSUSE Tumbleweed
       CPE OS Name: cpe:/o:opensuse:tumbleweed:20191110
            Kernel: Linux 5.3.8-1-default
      Architecture: x86-64
Connection to 192.168.121.111 closed.
```
I'm not using the latest Vagrant version available but I don't think that could be an issue.
```
$ vagrant version
Installed Version: 2.2.5
```

**Comment by dcermak** [comment]
Victor Morales <notifications@github.com> writes:

> Hey @dcermak , thanks for responding to this issue. I just tried with the latest available box  but it seems like it's not setting up the host name.
>
> ```
> $ cat Vagrantfile 
> Vagrant.configure("2") do |config|
>   config.vm.box = "opensuse/Tumbleweed.x86_64"
>   config.vm.box_version = "1.0.20191110"
>   config.vm.hostname = "testing"
> end
> $ vagrant ssh -- -t hostnamectl
>    Static hostname: n/a
> Transient hostname: localhost
>          Icon name: computer-vm
>            Chassis: vm
>         Machine ID: 08560f5137b643d9bb004bdee24ee10e
>            Boot ID: 652ca5d5aa3a41c28b3c8c89c566f74d
>     Virtualization: kvm
>   Operating System: openSUSE Tumbleweed
>        CPE OS Name: cpe:/o:opensuse:tumbleweed:20191110
>             Kernel: Linux 5.3.8-1-default
>       Architecture: x86-64
> Connection to 192.168.121.111 closed.
> ```
> I'm not using the latest Vagrant version available but I don't think that could be an issue.
> ```
> $ vagrant version
> Installed Version: 2.2.5
> ```

That is actually the issue, because the fix didn't make it into
2.2.5. You'll have to update vagrant to 2.2.6. If you are running
openSUSE yourself, then you can get the latest version from the
Virtualization:vagrant project on https://build.opensuse.org

**Comment by electrocucaracha** [comment]
Ok, I have updated vagrant to 2.2.6 version and now works

```bash
$ vagrant version
Installed Version: 2.2.6
Latest Version: 2.2.6
 
You're running an up-to-date version of Vagrant!
$ vagrant ssh -- -t hostnamectl
   Static hostname: testing
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 3cf73258a8af48acafdd17b7b33e6c88
           Boot ID: 2425415870a54e1eb5ecdeff293a7357
    Virtualization: kvm
  Operating System: openSUSE Tumbleweed
       CPE OS Name: cpe:/o:opensuse:tumbleweed:20191110
            Kernel: Linux 5.3.8-1-default
      Architecture: x86-64
Connection to 192.168.121.126 closed.
```
Maybe this can be prevented adding a **require_version** value like 
```bash
$ cat ~/.vagrant.d/boxes/opensuse-VAGRANTSLASH-Tumbleweed.x86_64/1.0.20191110/libvirt/Vagrantfile 
Vagrant.require_version ">= 2.2.6"

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
  end
end
```
 Thanks @dcermak

**Comment by dcermak** [comment]
Victor Morales <notifications@github.com> writes:

> Ok, I have updated vagrant to 2.2.6 version and now works
>
> ```bash
> $ vagrant version
> Installed Version: 2.2.6
> Latest Version: 2.2.6
>  
> You're running an up-to-date version of Vagrant!
> $ vagrant ssh -- -t hostnamectl
>    Static hostname: testing
>          Icon name: computer-vm
>            Chassis: vm
>         Machine ID: 3cf73258a8af48acafdd17b7b33e6c88
>            Boot ID: 2425415870a54e1eb5ecdeff293a7357
>     Virtualization: kvm
>   Operating System: openSUSE Tumbleweed
>        CPE OS Name: cpe:/o:opensuse:tumbleweed:20191110
>             Kernel: Linux 5.3.8-1-default
>       Architecture: x86-64
> Connection to 192.168.121.126 closed.
> ```
> Maybe this can be prevented adding a **require_version** value like 
> ```bash
> $ cat ~/.vagrant.d/boxes/opensuse-VAGRANTSLASH-Tumbleweed.x86_64/1.0.20191110/libvirt/Vagrantfile 
> Vagrant.require_version ">= 2.2.6"
>
> Vagrant.configure("2") do |config|
>   config.vm.synced_folder ".", "/vagrant", type: "rsync"
>   config.vm.provider :libvirt do |libvirt|
>     libvirt.driver = "kvm"
>   end
> end
> ```

Wouldn't that break this box for everyone without the latest vagrant
version? That's imho too drastic because of a (imho) minor vagrant bug.

>  Thanks @dcermak

You are very much welcome. Thank you for using the openSUSE vagrant
boxes!
