### ISSUE TITLE
opensuse 15.1: vagrant 2.2.0-lp151.1.33 + virtualbox 6.0.12-lp151-2.9.1 not compatible

### ISSUE THREAD

**Issue by peterdd** [openSUSE/vagrant#42]
The versions that are installed with YaST2  are not compatible.

![1570062311](https://user-images.githubusercontent.com/1839154/66090929-bd3fd900-e585-11e9-88bd-51ee3983334f.png)

**Comment by peterdd** [comment]
Related issue: https://github.com/hashicorp/vagrant/issues/11026

**Comment by dcermak** [comment]
This looks like an upstream or packaging issue to me and not like something that is related to the image recipes of the openSUSE distribution.

If you believe that this is a packaging issue, please open a bug in Bugzilla: https://bugzilla.opensuse.org/enter_bug.cgi?classification=openSUSE

**Comment by peterdd** [comment]
Maybe it is because I do not understand the first sentence of the README.md 

> This repository stores our Packer definitions of various versions of openSUSE for running Vagrant.

Running openSUSE as host or as guest?
Maybe requires some rewording.

And I avoid to start that bugzilla-novell-microfocus-wiki-mailinglist-journey unless I am forced to take the pain.

**Comment by dcermak** [comment]
This repository stores the recipes to build SUSE guest images, so this is very much the wrong place to report this issue.

You should be able to resolve the issue by adding the [Virtualization:vagrant.repo](https://download.opensuse.org/repositories/Virtualization:/vagrant/openSUSE_Leap_15.1/Virtualization:vagrant.repo) and then upgrading your system:
``` ShellSession
$ zypper addrepo https://download.opensuse.org/repositories/Virtualization:/vagrant/openSUSE_Leap_15.1/Virtualization:vagrant.repo
$ zypper dup --allow-vendor-change
```

If you've still got problems, then I'd suggest to ask in one of the support chat rooms, e.g. on Freenode or on Discord.
