### ISSUE TITLE
provide a more recent (42.2) image

### ISSUE THREAD

**Issue by muelli** [openSUSE/vagrant#5]
I have the feeling the currently available image on hashicorp's atlas is a bit outdated.  It would be nice to have a more recent version.

**Comment by thomasbilk** [comment]
I was looking for 42.2 images today (2017-03-24) and could not find them anywhere. Neither on the openSUSE [server](http://download.opensuse.org/vagrant/) nor on [Atlas](https://atlas.hashicorp.com/opensuse/). Can you please add them again?

**Comment by hwoarang** [comment]
I have built a 42.2 virtualbox image and testing it at the moment. Once I build a libvirt one I will publish both and close this bug

**Comment by hwoarang** [comment]
libvirt takes a while because I need to find a proper hosting service since atlas does not understand the libvirt provider. However, the virtualbox image is now available so I am closing this bug. Once the libvirt image is online I will update the readme with the new location.
