### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by PI-Victor** [openSUSE/vagrant#9]
most of the links in the readme, that point to the boxes, are broken.
the 42.2 images aren't in http://download.opensuse.org/vagrant/ (and a few others as well)
I'd suggest just removing the specific links for each box and pointing directly to http://download.opensuse.org/vagrant/ so that they don't get broken in the future.

**Comment by tboerger** [comment]
The links are fine, as long as the images are uploaded

**Comment by gmmeyer** [comment]
The tumbleweed one is not, it points to 1.0.1, but there is only 1.0.0 in the http://download.opensuse.org/vagrant/ repository
